run:
  skip-dirs:
    - testdata
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 10
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true
  goconst:
    min-occurrences: 4
  gofmt:
    simplify: true
  lll:
    line-length: 120
    tab-width: 4
  funlen:
    lines: 100
  gocritic:
    disabled-checks:
      - paramTypeCombine
      - emptyStringTest
      - ifElseChain
      - commentFormatting
      - unnamedResult
    enabled-tags:
      - performance
      - diagnostic
      - style
    settings:
      hugeParam:
        sizeThreshold: 512
      rangeValCopy:
        sizeThreshold: 512
  wsl:
    allow-assign-and-call: false

linters:
  enable-all: true
  #disable-all: true
  disable:
    - godox
    - gofumpt
    - forbidigo
    - paralleltest

issues:
  exclude-use-default: false
  exclude-rules:
    - path: .*_test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - lll
        - goconst
        - govet
        - funlen
    - text: "package comment should not have leading space"
      linters:
        - golint
    - text: "should have a package comment, unless it's in another file for this package"
      linters:
        - golint
    - text: "at least one file in a package should have a package comment"
      linters:
        - stylecheck
    - text: "exported (.*) should have comment .*or be unexported"
      linters:
        - golint
    - text: "exported (.*) should have comment .*or be unexported"
      linters:
        - revive
    - text: "exported const (.*) should have comment [(]or a comment on this block[)] or be unexported"
      linters:
        - golint
