// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Ingredient Meal Ingredient
//
// An ingredient for a meal
//
// swagger:model Ingredient
type Ingredient struct {

	// description
	Description string `json:"description,omitempty"`

	// id
	ID int64 `json:"id,omitempty" gorm:"primaryKey"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this ingredient
func (m *Ingredient) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ingredient based on context it is used
func (m *Ingredient) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Ingredient) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Ingredient) UnmarshalBinary(b []byte) error {
	var res Ingredient
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
