// Code generated by go-swagger; DO NOT EDIT.

package meal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pgillich/meals-demo/internal/models"
)

// DeleteMealOKCode is the HTTP code returned for type DeleteMealOK
const DeleteMealOKCode int = 200

/*DeleteMealOK successful operation

swagger:response deleteMealOK
*/
type DeleteMealOK struct {
}

// NewDeleteMealOK creates DeleteMealOK with default headers values
func NewDeleteMealOK() *DeleteMealOK {

	return &DeleteMealOK{}
}

// WriteResponse to the client
func (o *DeleteMealOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteMealUnauthorizedCode is the HTTP code returned for type DeleteMealUnauthorized
const DeleteMealUnauthorizedCode int = 401

/*DeleteMealUnauthorized Unauthorized

swagger:response deleteMealUnauthorized
*/
type DeleteMealUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewDeleteMealUnauthorized creates DeleteMealUnauthorized with default headers values
func NewDeleteMealUnauthorized() *DeleteMealUnauthorized {

	return &DeleteMealUnauthorized{}
}

// WithPayload adds the payload to the delete meal unauthorized response
func (o *DeleteMealUnauthorized) WithPayload(payload *models.APIError) *DeleteMealUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete meal unauthorized response
func (o *DeleteMealUnauthorized) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteMealUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteMealInternalServerErrorCode is the HTTP code returned for type DeleteMealInternalServerError
const DeleteMealInternalServerErrorCode int = 500

/*DeleteMealInternalServerError Error

swagger:response deleteMealInternalServerError
*/
type DeleteMealInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewDeleteMealInternalServerError creates DeleteMealInternalServerError with default headers values
func NewDeleteMealInternalServerError() *DeleteMealInternalServerError {

	return &DeleteMealInternalServerError{}
}

// WithPayload adds the payload to the delete meal internal server error response
func (o *DeleteMealInternalServerError) WithPayload(payload *models.APIError) *DeleteMealInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete meal internal server error response
func (o *DeleteMealInternalServerError) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteMealInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
