// Code generated by go-swagger; DO NOT EDIT.

package meal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewFindMealsByTagParams creates a new FindMealsByTagParams object
//
// There are no default values defined in the spec.
func NewFindMealsByTagParams() FindMealsByTagParams {

	return FindMealsByTagParams{}
}

// FindMealsByTagParams contains all the bound params for the find meals by tag operation
// typically these are obtained from a http.Request
//
// swagger:parameters findMealsByTag
type FindMealsByTagParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Tag to filter by
	  In: query
	*/
	Tag *int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewFindMealsByTagParams() beforehand.
func (o *FindMealsByTagParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qTag, qhkTag, _ := qs.GetOK("tag")
	if err := o.bindTag(qTag, qhkTag, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindTag binds and validates parameter Tag from query.
func (o *FindMealsByTagParams) bindTag(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("tag", "query", "int64", raw)
	}
	o.Tag = &value

	return nil
}
