// Code generated by go-swagger; DO NOT EDIT.

package meal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetMealByIDHandlerFunc turns a function with the right signature into a get meal by Id handler
type GetMealByIDHandlerFunc func(GetMealByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMealByIDHandlerFunc) Handle(params GetMealByIDParams) middleware.Responder {
	return fn(params)
}

// GetMealByIDHandler interface for that can handle valid get meal by Id params
type GetMealByIDHandler interface {
	Handle(GetMealByIDParams) middleware.Responder
}

// NewGetMealByID creates a new http.Handler for the get meal by Id operation
func NewGetMealByID(ctx *middleware.Context, handler GetMealByIDHandler) *GetMealByID {
	return &GetMealByID{Context: ctx, Handler: handler}
}

/* GetMealByID swagger:route GET /meal/{id} meal getMealById

Find meal by ID

Returns a single meal

*/
type GetMealByID struct {
	Context *middleware.Context
	Handler GetMealByIDHandler
}

func (o *GetMealByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetMealByIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
