// Code generated by go-swagger; DO NOT EDIT.

package meal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pgillich/meals-demo/internal/models"
)

// GetTagsOKCode is the HTTP code returned for type GetTagsOK
const GetTagsOKCode int = 200

/*GetTagsOK successful operation

swagger:response getTagsOK
*/
type GetTagsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Tag `json:"body,omitempty"`
}

// NewGetTagsOK creates GetTagsOK with default headers values
func NewGetTagsOK() *GetTagsOK {

	return &GetTagsOK{}
}

// WithPayload adds the payload to the get tags o k response
func (o *GetTagsOK) WithPayload(payload []*models.Tag) *GetTagsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tags o k response
func (o *GetTagsOK) SetPayload(payload []*models.Tag) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTagsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Tag, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetTagsInternalServerErrorCode is the HTTP code returned for type GetTagsInternalServerError
const GetTagsInternalServerErrorCode int = 500

/*GetTagsInternalServerError Invalid tag value

swagger:response getTagsInternalServerError
*/
type GetTagsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewGetTagsInternalServerError creates GetTagsInternalServerError with default headers values
func NewGetTagsInternalServerError() *GetTagsInternalServerError {

	return &GetTagsInternalServerError{}
}

// WithPayload adds the payload to the get tags internal server error response
func (o *GetTagsInternalServerError) WithPayload(payload *models.APIError) *GetTagsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tags internal server error response
func (o *GetTagsInternalServerError) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTagsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
