// Code generated by go-swagger; DO NOT EDIT.

package meal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateMealHandlerFunc turns a function with the right signature into a update meal handler
type UpdateMealHandlerFunc func(UpdateMealParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateMealHandlerFunc) Handle(params UpdateMealParams) middleware.Responder {
	return fn(params)
}

// UpdateMealHandler interface for that can handle valid update meal params
type UpdateMealHandler interface {
	Handle(UpdateMealParams) middleware.Responder
}

// NewUpdateMeal creates a new http.Handler for the update meal operation
func NewUpdateMeal(ctx *middleware.Context, handler UpdateMealHandler) *UpdateMeal {
	return &UpdateMeal{Context: ctx, Handler: handler}
}

/* UpdateMeal swagger:route PUT /meal/{id} meal updateMeal

Update an existing meal

*/
type UpdateMeal struct {
	Context *middleware.Context
	Handler UpdateMealHandler
}

func (o *UpdateMeal) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateMealParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
