// Code generated by go-swagger; DO NOT EDIT.

// Package restapi OpenAPI Foodstore
//
//  This is demo for a foodstore (meals) service
//  Schemes:
//    http
//  Host: foodstore.kind-01.company.com
//  BasePath: /v1
//  Version: 1.0.0
//  License: Apache-2.0 https://www.apache.org/licenses/LICENSE-2.0.html
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
