// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.3 DO NOT EDIT.
package api

const (
	JWTScopes = "JWT.Scopes"
)

// ApiError defines model for ApiError.
type ApiError struct {
	Message string `json:"message"`
}

// Ingredient An ingredient for a meal
type Ingredient struct {
	Description string `json:"description"`
	Id          int64  `gorm:"primaryKey" json:"id"`
	Name        string `json:"name"`
}

// LoginInfo defines model for LoginInfo.
type LoginInfo struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// LoginSuccess defines model for LoginSuccess.
type LoginSuccess struct {
	Success bool   `json:"success"`
	Token   string `json:"token"`
}

// Meal A meal
type Meal struct {
	Description string       `json:"description"`
	Id          int64        `gorm:"primaryKey" json:"id"`
	Ingredients []Ingredient `gorm:"many2many:meal_ingredients" json:"ingredients"`
	Kcal        float32      `json:"kcal"`
	Name        string       `json:"name" valid:"customNameValidator"`
	PictureUrl  string       `json:"pictureUrl"`
	Price       float32      `json:"price"`
	Tags        []Tag        `gorm:"many2many:meal_tags" json:"tags"`
}

// Tag A tag for a meal
type Tag struct {
	Id   int64  `gorm:"primaryKey" json:"id"`
	Name string `json:"name"`
}

// User defines model for User.
type User struct {
	Email    string `json:"email"`
	FullName string `json:"fullName"`
	Password string `json:"password"`
}

// Version Version and build info
type Version struct {
	AppName   string `json:"appName"`
	BuildTime string `json:"buildTime"`
	GoMod     string `json:"goMod"`
	Version   string `json:"version"`
}

// FindMealsByTagParams defines parameters for FindMealsByTag.
type FindMealsByTagParams struct {
	// Tag Tag to filter by
	Tag *int64 `form:"tag,omitempty" json:"tag,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginInfo

// CreateMealJSONRequestBody defines body for CreateMeal for application/json ContentType.
type CreateMealJSONRequestBody = Meal

// UpdateMealJSONRequestBody defines body for UpdateMeal for application/json ContentType.
type UpdateMealJSONRequestBody = Meal
