replicaCount: 1

mealService:
  dbDSN: AgDYZpI/tEVocb6JyrWszjRc1E/KrWAu26hCXpBhzVp7rDPxcAi+Icft/58PcsTnMYc+ffYcf75UduMsaxdn61FcXAvyA32hf4fkeTVddT8lWxOrpYgZh4JqJwa7X9u5PMceeBe9pdHxubShOaWjbgQXYrHABWKkX/D23GIzpYlksyc1PIjFtGGYXxRjcGNa4tzpUB2IKbNmg8m82dgdFEVCBIUeAd726X2sEV2Y70vsW2URFQ5WQzobL6xNFOpyX3bRlBuRK5bfENnZ/ZD13Ezz/Qf0+7z3UdqqYyyskxJyX8xW/kpeJSGaWE9xBqkPuv3YUHSepjaTRYWlJaygYFcPN4R+5MfyS6XRRKlzE0oQ28PfAcfSkDCw2WJEAgWgdMxMWhoBU/5XL0zwro/6+bwTgsgHYvWt+6/kbkXZIuw1koN3bxNT1fCTAhVXSxOzvkivBlIAebQ/OL8+yz6572mQnVsfE7ZG4RJ5V9wGyJnUIwPtKl53wy7lh6Vh6uvL31EvY2oj7uvJvHQoIbrojTLkZhPCDXRVBsns2PBIiTqwnsOjMZ8QeLvGEzDpSPk0SH86MDIP+PQ9fe5JNhRWHbEIp55dNmAYPZ4twsysA0kWAp7zt3p7go6YBxdN2oOkLyqSXheNp5w4gVkQpsen18ulQ29cCTRtkl2WclUPbJrrX39pn/hJthX0ZEFQFadkYD91ylB0RkUAw9uZfkwtIsWWvv88OrNmH1RySeeoAEbmeCRbIhZHaHKWzhhcd/C+LaueeolbjxjIuAMq6OcNUYIcdQrSg4vAVVBR3jTntNZP/CnEAQGpmJoIJdd5L053mtEYHvvuD6d3p/NxFwr4DYsqw1hZ53CXs0t9s2eI/NX9ICqdI6kRHgPCr1tw5LwjHWpXOZfAHLvqJ/D+
  sealedSecret: true

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: foodstore-pgillich.mooo.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: foodstore
              port:
                number: 80
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

