{{ if .Values.mealService.sealedSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: meal-secret
spec:
  encryptedData:
    SERVICE_DB_DSN: {{ .Values.mealService.dbDSN }}
    SERVICE_JWT_KEY: {{ .Values.mealService.jwtKey }}
  template:
    metadata:
      name: meal-secret
      namespace: {{ .Release.Namespace }}
{{ end }}
