##
## Starter Kit configuration for Sealed Secrets
##

# Make sure Ingress is disabled for security reasons
ingress:
  enabled: false

metrics:
  serviceMonitor:
    enabled: true

  dashboards:
    create: true
