// Code generated by go-swagger; DO NOT EDIT.

package info

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetLivezOKCode is the HTTP code returned for type GetLivezOK
const GetLivezOKCode int = 200

/*GetLivezOK successful operation

swagger:response getLivezOK
*/
type GetLivezOK struct {
}

// NewGetLivezOK creates GetLivezOK with default headers values
func NewGetLivezOK() *GetLivezOK {

	return &GetLivezOK{}
}

// WriteResponse to the client
func (o *GetLivezOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
