// Code generated by go-swagger; DO NOT EDIT.

package info

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetLivezHandlerFunc turns a function with the right signature into a get livez handler
type GetLivezHandlerFunc func(GetLivezParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetLivezHandlerFunc) Handle(params GetLivezParams) middleware.Responder {
	return fn(params)
}

// GetLivezHandler interface for that can handle valid get livez params
type GetLivezHandler interface {
	Handle(GetLivezParams) middleware.Responder
}

// NewGetLivez creates a new http.Handler for the get livez operation
func NewGetLivez(ctx *middleware.Context, handler GetLivezHandler) *GetLivez {
	return &GetLivez{Context: ctx, Handler: handler}
}

/* GetLivez swagger:route GET /livez info getLivez

Liveness status for orchestrator

Returns OK

*/
type GetLivez struct {
	Context *middleware.Context
	Handler GetLivezHandler
}

func (o *GetLivez) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetLivezParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
