apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:
  - namespace.yaml
  - postgres-configmap.yaml
  - postgres-storage.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
